import { PromptFieldConfig, ProviderConfig } from "./types";

// ── Prompt Field Configurations with Presets ──
export const PROMPT_FIELDS: PromptFieldConfig[] = [
  {
    key: "design",
    label: { en: "Design", es: "Diseño" },
    icon: "palette",
    presets: {
      en: [
        { id: "design-none", label: "None", text: "" },
        {
          id: "design-corporate",
          label: "Corporate Clean",
          text: "Use a professional corporate style with a navy blue and white color palette. Clean sans-serif typography (Calibri or Arial). Minimal decorative elements. Consistent header/footer layout with logo placeholder. Use subtle gradients and geometric accent shapes.",
        },
        {
          id: "design-creative",
          label: "Creative & Bold",
          text: "Use a vibrant, modern design with bold colors (electric blue, coral, yellow accents). Large impactful typography with mixed weights. Asymmetric layouts. Use overlapping shapes and dynamic compositions. High contrast between text and backgrounds.",
        },
        {
          id: "design-minimal",
          label: "Minimalist",
          text: "Ultra-clean minimalist design. Black and white with one accent color (teal). Generous white space. Thin sans-serif fonts. No borders or unnecessary decorations. Content-first approach with simple, elegant layouts.",
        },
        {
          id: "design-academic",
          label: "Academic / Research",
          text: "Formal academic style suitable for research presentations. Structured grid layout with clear hierarchy. Serif fonts for headings, sans-serif for body. Muted earth tones. Space for citations and references. Clean data visualization areas.",
        },
        {
          id: "design-startup",
          label: "Startup Pitch Deck",
          text: "Modern startup pitch deck style. Dark backgrounds with neon accent gradients (purple to blue). Bold headlines. Full-bleed imagery sections. Metric-focused layouts with large numbers. Tech-forward aesthetic.",
        },
      ],
      es: [
        { id: "design-none", label: "Ninguno", text: "" },
        {
          id: "design-corporate",
          label: "Corporativo Limpio",
          text: "Usa un estilo corporativo profesional con paleta de colores azul marino y blanco. Tipografía sans-serif limpia (Calibri o Arial). Elementos decorativos mínimos. Diseño consistente de encabezado/pie de página con espacio para logo. Usa degradados sutiles y formas geométricas de acento.",
        },
        {
          id: "design-creative",
          label: "Creativo y Audaz",
          text: "Usa un diseño vibrante y moderno con colores audaces (azul eléctrico, coral, acentos amarillos). Tipografía grande e impactante con pesos mixtos. Diseños asimétricos. Usa formas superpuestas y composiciones dinámicas. Alto contraste entre texto y fondos.",
        },
        {
          id: "design-minimal",
          label: "Minimalista",
          text: "Diseño minimalista ultra-limpio. Blanco y negro con un color de acento (turquesa). Amplio espacio en blanco. Fuentes sans-serif delgadas. Sin bordes ni decoraciones innecesarias. Enfoque en contenido con diseños simples y elegantes.",
        },
        {
          id: "design-academic",
          label: "Académico / Investigación",
          text: "Estilo académico formal adecuado para presentaciones de investigación. Diseño de cuadrícula estructurado con jerarquía clara. Fuentes serif para títulos, sans-serif para cuerpo. Tonos tierra apagados. Espacio para citas y referencias. Áreas limpias de visualización de datos.",
        },
        {
          id: "design-startup",
          label: "Pitch Deck Startup",
          text: "Estilo moderno de pitch deck para startups. Fondos oscuros con degradados de acento neón (púrpura a azul). Titulares audaces. Secciones de imagen a sangre completa. Diseños enfocados en métricas con números grandes. Estética tecnológica.",
        },
      ],
    },
  },
  {
    key: "text",
    label: { en: "Slide Text", es: "Texto de Diapositivas" },
    icon: "text",
    presets: {
      en: [
        { id: "text-none", label: "None", text: "" },
        {
          id: "text-detailed",
          label: "Detailed & Informative",
          text: "Generate thorough, well-researched content with specific data points and examples. Use clear topic sentences with supporting details. Informative tone. Organize in a logical sequential flow, building from introduction to conclusions.",
        },
        {
          id: "text-concise",
          label: "Concise Bullet Points",
          text: "Generate concise, impactful bullet points. Maximum 5-6 words per bullet. Key takeaways only. Action verbs to start each point. No full sentences — fragments that capture the essence. Clean linear progression.",
        },
        {
          id: "text-storytelling",
          label: "Storytelling Narrative",
          text: "Frame as a compelling narrative. Start with a hook or provocative question. Build tension through problem identification, present the solution as a journey. Emotional language with relatable examples. End with a powerful call to action.",
        },
        {
          id: "text-technical",
          label: "Technical Deep-Dive",
          text: "Technically precise content with code snippets, architecture descriptions, and specifications where appropriate. Proper technical terminology. Problem-solution structure. Include performance metrics and benchmarks. Target: developers and engineers.",
        },
        {
          id: "text-executive",
          label: "Executive Summary",
          text: "Executive-level content focused on business impact. Lead with key outcomes and ROI. High-level strategic language. Market data and competitive positioning. Pyramid structure: main conclusion first, then supporting arguments. Formal professional tone.",
        },
      ],
      es: [
        { id: "text-none", label: "Ninguno", text: "" },
        {
          id: "text-detailed",
          label: "Detallado e Informativo",
          text: "Genera contenido exhaustivo y bien investigado con datos específicos y ejemplos. Oraciones temáticas claras con detalles de apoyo. Tono informativo. Organiza en flujo lógico secuencial, desde introducción hasta conclusiones.",
        },
        {
          id: "text-concise",
          label: "Viñetas Concisas",
          text: "Genera viñetas concisas e impactantes. Máximo 5-6 palabras por viñeta. Solo puntos clave. Verbos de acción para comenzar. Sin oraciones completas — fragmentos que capturen la esencia. Progresión lineal limpia.",
        },
        {
          id: "text-storytelling",
          label: "Narrativa / Storytelling",
          text: "Enmarca como narrativa convincente. Comienza con un gancho o pregunta provocadora. Construye tensión identificando el problema, presenta la solución como un viaje. Lenguaje emocional con ejemplos identificables. Termina con llamado a la acción.",
        },
        {
          id: "text-technical",
          label: "Inmersión Técnica",
          text: "Contenido técnicamente preciso con fragmentos de código, descripciones de arquitectura y especificaciones. Terminología técnica adecuada. Estructura problema-solución. Métricas de rendimiento. Audiencia: desarrolladores e ingenieros.",
        },
        {
          id: "text-executive",
          label: "Resumen Ejecutivo",
          text: "Contenido de nivel ejecutivo enfocado en impacto empresarial. Lidera con resultados clave y ROI. Lenguaje estratégico de alto nivel. Datos de mercado y posicionamiento. Estructura pirámide: conclusión principal primero, luego argumentos. Tono profesional formal.",
        },
      ],
    },
  },
  {
    key: "notes",
    label: { en: "Presenter Notes", es: "Notas del Presentador" },
    icon: "mic",
    presets: {
      en: [
        { id: "notes-none", label: "None", text: "" },
        {
          id: "notes-detailed",
          label: "Detailed Script",
          text: "Write detailed presenter notes as a full spoken script. Include transitions between slides, key talking points expanded into paragraphs, timing cues, and audience engagement prompts. The presenter should be able to read these notes verbatim.",
        },
        {
          id: "notes-keywords",
          label: "Keywords & Cues",
          text: "Write brief keyword-based presenter notes. Short bullet points with key terms to mention, data points to cite, and transition phrases. Just enough to jog the presenter's memory — not a full script.",
        },
        {
          id: "notes-qa",
          label: "Q&A Ready",
          text: "Write presenter notes that anticipate audience questions. Include the main talking points plus likely questions and suggested answers. Add supporting data and sources the presenter can reference if challenged.",
        },
        {
          id: "notes-storyteller",
          label: "Storyteller Guide",
          text: "Write presenter notes as storytelling guides. Include the narrative arc for each slide, emotional beats to hit, anecdotes or examples to share, pauses for effect, and audience interaction moments.",
        },
        {
          id: "notes-minimal",
          label: "Minimal Reminders",
          text: "Write very brief presenter notes — 1-2 short lines per slide maximum. Just the essential reminder of what to cover. The presenter already knows the material well and only needs minimal prompts.",
        },
      ],
      es: [
        { id: "notes-none", label: "Ninguno", text: "" },
        {
          id: "notes-detailed",
          label: "Guión Detallado",
          text: "Escribe notas detalladas como guión hablado completo. Incluye transiciones entre diapositivas, puntos clave expandidos en párrafos, indicaciones de tiempo y momentos de interacción. El presentador debería poder leer estas notas tal cual.",
        },
        {
          id: "notes-keywords",
          label: "Palabras Clave",
          text: "Escribe notas breves basadas en palabras clave. Viñetas cortas con términos a mencionar, datos a citar y frases de transición. Solo lo necesario para recordar al presentador — no un guión completo.",
        },
        {
          id: "notes-qa",
          label: "Preparado para Preguntas",
          text: "Escribe notas que anticipen preguntas de la audiencia. Incluye puntos principales más preguntas probables y respuestas sugeridas. Agrega datos de apoyo y fuentes que el presentador pueda referenciar.",
        },
        {
          id: "notes-storyteller",
          label: "Guía Narrativa",
          text: "Escribe notas como guías narrativas. Incluye el arco narrativo de cada diapositiva, momentos emocionales clave, anécdotas o ejemplos para compartir, pausas dramáticas y momentos de interacción.",
        },
        {
          id: "notes-minimal",
          label: "Recordatorios Mínimos",
          text: "Escribe notas muy breves — máximo 1-2 líneas cortas por diapositiva. Solo el recordatorio esencial de qué cubrir. El presentador ya conoce bien el material y solo necesita indicaciones mínimas.",
        },
      ],
    },
  },
];

// ── Default Provider Configs ──
export const DEFAULT_PROVIDERS: ProviderConfig[] = [
  {
    id: "openrouter",
    name: "OpenRouter",
    models: [],
  },
  {
    id: "gemini",
    name: "Google Gemini",
    models: [],
  },
  {
    id: "claude",
    name: "Anthropic Claude",
    models: [],
  },
  {
    id: "openai",
    name: "OpenAI",
    models: [],
  },
];

// ── UI Translations ──
export const UI_TEXT = {
  en: {
    appName: "TrueSlides",
    tagline: "AI-Powered Presentation Generator",
    settings: "Settings",
    general: "General",
    ai: "AI",
    language: "Interface Language",
    outputLanguage: "Presentation and Notes Language",
    provider: "Provider",
    model: "Model",
    apiKey: "API Key",
    save: "Save",
    cancel: "Cancel",
    generate: "Generate Presentation",
    generating: "Generating...",
    download: "Download PPTX",
    downloadPdf: "Download PDF",
    downloadNotes: "Download Notes",
    slideCount: "Number of Slides",
    custom: "Custom",
    uploadFile: "Upload Document",
    pasteText: "Or paste text directly",
    dragDrop: "Drag & drop PDF, DOCX, or TXT",
    browse: "Browse Files",
    imageLayout: "Image Layout",
    imageFull: "Full Bleed (1)",
    imageTwo: "2 Images",
    imageThree: "3 Images",
    imageCollage: "Collage (4)",
    imageCombined: "Combined (auto)",
    stretchImages: "Stretch images to fill slide",
    showImageSource: "Show image source in corner",
    imageSourceFontColor: "Image source text color",
    textDensity: "Text Density",
    searchModels: "Search models...",
    pinned: "Pinned",
    noModels: "No models loaded. Enter API key and save.",
    loadModels: "Load Models",
    choosePreset: "Choose a preset...",
    editor: "Slide Editor",
    editorPlaceholder: "Describe changes to apply...",
    applyChanges: "Apply Changes",
    allSlides: "All Slides",
    slide: "Slide",
    presenterNotes: "Presenter Notes",
    error: "Error",
    retry: "Retry",
    close: "Close",
    unsupportedFile: "Unsupported file type. Please upload PDF, DOCX, or TXT.",
    emptyInput: "Please upload a document or paste text.",
    apiError: "AI API error. Please check your API key and try again.",
    emptyResponse: "AI returned an empty response. Please try again.",
    fetchingModels: "Fetching models...",
    inputPrice: "Input",
    outputPrice: "Output",
    perMillion: "/1M tokens",
    promptsTab: "Prompts",
    promptManager: "Prompt Manager",
    addPrompt: "Add Prompt",
    editPrompt: "Edit",
    deletePrompt: "Delete",
    promptName: "Prompt Name",
    promptText: "Prompt Text",
    noCustomPrompts: "No custom prompts yet. Add one above.",
    designSection: "Design",
    textSection: "Slide Text",
    notesSection: "Presenter Notes",
    accentColor: "Accent Color",
    applyToAll: "Apply to All",
    applyToSlide: "This Slide",
    hexPlaceholder: "#6366F1",
    colorPresets: "Color Presets",
    fetchingImages: "Fetching images...",
    editApplied: "Changes applied",
    images: "Images",
    imageSources: "Image Sources",
    imageSourcesDesc: "Select which image sources to use when fetching slide images. Wikimedia Commons is always free. Others require a free API key.",
    getApiKey: "Get free API key",
    keyStored: "Key stored securely",
    noKeyWarning: "API key required to enable",
    remove: "Remove",
    generateAiImage: "Generate with AI",
    aiImageTitle: "Generate Image with AI",
    aiImageProvider: "Provider",
    aiImageModel: "Model",
    aiImagePrompt: "Prompt",
    aiImageAutoPrompt: "Automatic (AI chooses best prompt)",
    aiImageGenerate: "Generate",
    aiImageGenerating: "Generating image...",
    aiImageSlot: "Image slot",
    aiImageNoKey: "Set up API key in Settings first",
    tabManual: "Manual Creator",
    tabCreator: "AI Creator",
    tabHome: "Home",
    tabHistory: "History",
    subTabCreate: "Create",
    subTabEdit: "Edit",
    manualSubTabList: "My Creations",
    manualSubTabEditor: "Editor",
    historyEmpty: "No presentations yet. Create one from the AI Creator tab.",
    manualSlideTitle: "Title",
    manualSlideSubtitle: "Subtitle",
    manualSlideBullets: "Bullet Points",
    manualSlideNotes: "Presenter Notes",
    manualAddTitle: "Add Title",
    manualAddSubtitle: "Add Subtitle",
    manualAddText: "Add Text",
    manualAddBullets: "Add Bullet Points",
    manualAddImage: "Add Image",
    manualAddYoutube: "Add YouTube Video",
    manualYoutubeUrlPrompt: "Paste YouTube video URL",
    manualYoutubeUrlPlaceholder: "https://www.youtube.com/watch?v=...",
    manualYoutubeInvalidUrl: "Invalid YouTube URL",
    manualAddSlide: "Add Slide",
    manualDuplicateSlide: "Duplicate",
    manualDeleteSlide: "Delete",
    manualDeleteSlideConfirm: "Are you sure you want to delete this slide?",
    manualSelectLayout: "Select Layout",
    manualSearchImages: "Search Images",
    manualFullscreen: "Fullscreen Editor",
    manualUndo: "Undo",
    manualRedo: "Redo",
    manualAlignLeft: "Align Left",
    manualAlignCenter: "Align Center",
    manualAlignRight: "Align Right",
    manualAlignTop: "Align Top",
    manualAlignMiddle: "Align Middle",
    manualAlignBottom: "Align Bottom",
    manualBringForward: "Bring Forward",
    manualSendBackward: "Send Backward",
    manualEditText: "Edit Text",
    manualRemoveElement: "Remove Element",
    manualNotesHint: "Notes become undoable after the field loses focus.",
    manualGenerateNotes: "Generate Notes with AI",
    manualGeneratingNotes: "Generating notes...",
    manualWriteNotes: "Write notes here...",
    manualNoSlides: "No slides yet. Click 'Add Slide' to get started.",
    manualLayoutTitle: "Title Slide",
    manualLayoutContent: "Content",
    manualLayoutImageText: "Image + Text",
    manualLayoutTwoColumn: "Two Columns",
    manualLayoutImageOnly: "Image Only",
    manualLayoutBlank: "Blank",
    historyCreated: "Created",
    historySlides: "slides",
    historyEdit: "Edit",
    historyDelete: "Delete",
    historyDeleteConfirm: "Are you sure you want to delete this presentation?",
    historySavedAuto: "Saved to history",
    historySearch: "Search history...",
    historyStatusRunning: "Running",
    historyStatusCompleted: "Completed",
    historyStatusError: "Error",
    historyColTitle: "Title",
    historyColType: "Type",
    historyColStatus: "Status",
    historyColProvider: "Provider",
    historyColSlides: "Slides",
    historyColDate: "Date",
    historyColActions: "Actions",
    historyTypePresentation: "Presentation",
    historyTypeNotes: "Notes",
    historyCompleted: "Completed",
    historyStop: "Stop",
    historyStopConfirm: "Are you sure you want to stop this generation?",
    historyImportManual: "Import to Manual Creator",
    historyInProgress: "In Progress",
    tabNotes: "Notes",
    notesUploadPptx: "Upload PowerPoint (.pptx)",
    notesUploadDoc: "Upload Document (PDF, DOCX, TXT)",
    notesDragPptx: "Drag & drop your .pptx file",
    notesDragDoc: "Drag & drop PDF, DOCX, or TXT",
    notesGenerate: "Generate Notes",
    notesGenerating: "Generating notes...",
    notesParsing: "Parsing PowerPoint...",
    notesAnalyzing: "Analyzing document...",
    notesProcessing: "Generating notes for slide",
    notesOf: "of",
    notesDone: "Notes generated!",
    notesSlide: "Slide",
    notesRegenerate: "Regenerate",
    notesRegenerateAll: "Regenerate All",
    notesCustomPrompt: "Custom instruction (optional)",
    notesCustomPromptPlaceholder: "e.g. Expand on the key points, focus more on...",
    notesExportPptx: "Export PPTX with Notes",
    notesBack: "Back",
    notesEmpty: "Upload a PowerPoint and a document to generate presenter notes.",
    notesIncludeExisting: "Include existing presenter notes",
    notesIncludeExistingDesc: "Use existing slide notes as guidance for the AI",
    notesUseVision: "Analyze slide visually",
    notesUseVisionDesc: "Send slide images to the AI for richer analysis (requires vision model)",
    notesDocDensity: "Document coverage",
    notesDocDensitySlideOnly: "Slide only",
    notesDocDensityFull: "Full document",
    notesParagraphs: "Paragraphs per note",
    notesParagraphsCustom: "No limit",
    notesNoProvider: "Select a provider and model first.",
    notesPrompt: "Notes Prompt",
    imageSearchTitle: "Search Images",
    imageSearchPlaceholder: "Search for images...",
    imageSearchButton: "Search",
    imageSearchSource: "Source",
    imageSearchAllSources: "All Sources",
    imageSearchNoResults: "No images found. Try a different search term.",
    imageSearchSearching: "Searching...",
    imageSearchSelect: "Select",
    imageSearchSlot: "Image slot",
    imageSearchLoadMore: "Load more results",
    imageSearchLoadingMore: "Loading more...",
    slideRegenerate: "Regenerate Slide",
    slideRegenerating: "Regenerating...",
    slideVariants: "Generate Variants",
    slideVariantsCount: "Options",
    slideVariantsGenerating: "Generating variants...",
    slideVariantsTitle: "Slide Variants",
    slideVariantsApply: "Use this variant",
    slideVariantsNone: "No variants generated.",
    speedOptimizations: "Speed Optimizations",
    speedOptimizationsDesc: "Reduce image search time by skipping redundant queries. Each option trades a small amount of image variety for faster generation.",
    speedCapFallbacks: "Limit fallback searches",
    speedCapFallbacksDesc: "Caps retry attempts when initial image searches return few results.",
    speedCapFallbacksGain: "Eliminates the slowest phase — can save 10-30s per generation.",
    speedCapFallbacksLoss: "Slides with niche topics may get fewer image options.",
    speedSkipCategory: "Skip category search",
    speedSkipCategoryDesc: "Disables Wikimedia category lookups (2 sequential API calls per slide).",
    speedSkipCategoryGain: "Saves ~2-5s per slide by removing redundant searches.",
    speedSkipCategoryLoss: "Slightly fewer results for broad/encyclopedic topics.",
    speedReduceQueries: "Fewer search queries",
    speedReduceQueriesDesc: "Uses 2 query variants per slide instead of 3.",
    speedReduceQueriesGain: "Saves ~1-2s per slide by reducing API calls.",
    speedReduceQueriesLoss: "Marginally less image diversity per slide.",
    speedLowerLimit: "Lower fetch limit",
    speedLowerLimitDesc: "Fetches fewer candidate images per query.",
    speedLowerLimitGain: "Faster responses and less data to process.",
    speedLowerLimitLoss: "Smaller pool to pick from — usually unnoticeable.",
    speedGain: "Gain",
    speedLoss: "Trade-off",
    dangerZone: "Danger Zone",
    dangerZoneDesc: "Irreversible actions. Proceed with caution.",
    dangerRemoveAiKeys: "Remove AI API Keys",
    dangerRemoveAiKeysDesc: "Delete all stored AI provider API keys (OpenRouter, Gemini, Claude, OpenAI).",
    dangerRemoveImageKeys: "Remove Image Integration Keys",
    dangerRemoveImageKeysDesc: "Delete all stored image source API keys (Unsplash, Pexels, Pixabay, Flickr, Europeana).",
    dangerRemoveManual: "Remove Manual Creations",
    dangerRemoveManualDesc: "Delete all manually created presentations.",
    dangerRemoveAiCreations: "Remove AI Creations",
    dangerRemoveAiCreationsDesc: "Delete all AI-generated presentations from history.",
    dangerRemoveNotes: "Remove Generated Notes",
    dangerRemoveNotesDesc: "Delete all generated notes projects from history.",
    dangerRemoveAllCreations: "Remove All Creations",
    dangerRemoveAllCreationsDesc: "Delete all presentations, notes, and manual creations.",
    dangerRemoveEverything: "Remove Everything",
    dangerRemoveEverythingDesc: "Delete all data: API keys, creations, history, and settings.",
    dangerConfirmTitle: "Are you sure?",
    dangerConfirmMessage: "This action cannot be undone.",
    dangerConfirmButton: "Yes, delete",
    dangerSuccess: "Done",
  },
  es: {
    appName: "TrueSlides",
    tagline: "Generador de Presentaciones con IA",
    settings: "Configuración",
    general: "General",
    ai: "IA",
    language: "Idioma de Interfaz",
    outputLanguage: "Idioma de la presentación y las notas",
    provider: "Proveedor",
    model: "Modelo",
    apiKey: "Clave API",
    save: "Guardar",
    cancel: "Cancelar",
    generate: "Generar Presentación",
    generating: "Generando...",
    download: "Descargar PPTX",
    downloadPdf: "Descargar PDF",
    downloadNotes: "Descargar Notas",
    slideCount: "Número de Diapositivas",
    custom: "Personalizado",
    uploadFile: "Subir Documento",
    pasteText: "O pega texto directamente",
    dragDrop: "Arrastra PDF, DOCX o TXT",
    browse: "Buscar Archivos",
    imageLayout: "Diseño de Imágenes",
    imageFull: "Completa (1)",
    imageTwo: "2 Imágenes",
    imageThree: "3 Imágenes",
    imageCollage: "Collage (4)",
    imageCombined: "Combinado (auto)",
    stretchImages: "Estirar imágenes para llenar diapositiva",
    showImageSource: "Mostrar fuente de imagen en esquina",
    imageSourceFontColor: "Color del texto de la fuente de imagen",
    textDensity: "Densidad de Texto",
    searchModels: "Buscar modelos...",
    pinned: "Fijado",
    noModels: "Sin modelos. Ingresa la clave API y guarda.",
    loadModels: "Cargar Modelos",
    choosePreset: "Elegir preset...",
    editor: "Editor de Diapositivas",
    editorPlaceholder: "Describe los cambios a aplicar...",
    applyChanges: "Aplicar Cambios",
    allSlides: "Todas las Diapositivas",
    slide: "Diapositiva",
    presenterNotes: "Notas del Presentador",
    error: "Error",
    retry: "Reintentar",
    close: "Cerrar",
    unsupportedFile: "Tipo de archivo no soportado. Sube PDF, DOCX o TXT.",
    emptyInput: "Por favor sube un documento o pega texto.",
    apiError: "Error de API. Verifica tu clave API e intenta de nuevo.",
    emptyResponse: "La IA devolvió una respuesta vacía. Intenta de nuevo.",
    fetchingModels: "Cargando modelos...",
    inputPrice: "Entrada",
    outputPrice: "Salida",
    perMillion: "/1M tokens",
    promptsTab: "Prompts",
    promptManager: "Gestor de Prompts",
    addPrompt: "Añadir Prompt",
    editPrompt: "Editar",
    deletePrompt: "Eliminar",
    promptName: "Nombre del Prompt",
    promptText: "Texto del Prompt",
    noCustomPrompts: "Aún no hay prompts personalizados. Añade uno arriba.",
    designSection: "Diseño",
    textSection: "Texto de Diapositivas",
    notesSection: "Notas del Presentador",
    accentColor: "Color de Acento",
    applyToAll: "Aplicar a Todas",
    applyToSlide: "Esta Diapositiva",
    hexPlaceholder: "#6366F1",
    colorPresets: "Colores",
    fetchingImages: "Buscando imágenes...",
    editApplied: "Cambios aplicados",
    images: "Imágenes",
    imageSources: "Fuentes de Imágenes",
    imageSourcesDesc: "Selecciona qué fuentes de imágenes usar al buscar fotos para las diapositivas. Wikimedia Commons es siempre gratuita. Las demás requieren una clave API gratuita.",
    getApiKey: "Obtener clave API gratis",
    keyStored: "Clave guardada de forma segura",
    noKeyWarning: "Se necesita clave API para activar",
    remove: "Eliminar",
    generateAiImage: "Generar con IA",
    aiImageTitle: "Generar Imagen con IA",
    aiImageProvider: "Proveedor",
    aiImageModel: "Modelo",
    aiImagePrompt: "Prompt",
    aiImageAutoPrompt: "Automático (la IA elige el mejor prompt)",
    aiImageGenerate: "Generar",
    aiImageGenerating: "Generando imagen...",
    aiImageSlot: "Slot de imagen",
    aiImageNoKey: "Configura la clave API en Ajustes primero",
    tabManual: "Creador Manual",
    tabCreator: "Creador IA",
    tabHome: "Inicio",
    tabHistory: "Historial",
    subTabCreate: "Crear",
    subTabEdit: "Editar",
    manualSubTabList: "Mis Creaciones",
    manualSubTabEditor: "Editor",
    historyEmpty: "Aún no hay presentaciones. Crea una desde la pestaña Creador IA.",
    manualSlideTitle: "Título",
    manualSlideSubtitle: "Subtítulo",
    manualSlideBullets: "Viñetas",
    manualSlideNotes: "Notas del Presentador",
    manualAddTitle: "Añadir Título",
    manualAddSubtitle: "Añadir Subtítulo",
    manualAddText: "Añadir Texto",
    manualAddBullets: "Añadir Viñetas",
    manualAddImage: "Añadir Imagen",
    manualAddYoutube: "Añadir Vídeo de YouTube",
    manualYoutubeUrlPrompt: "Pega la URL del vídeo de YouTube",
    manualYoutubeUrlPlaceholder: "https://www.youtube.com/watch?v=...",
    manualYoutubeInvalidUrl: "URL de YouTube no válida",
    manualAddSlide: "Añadir Diapositiva",
    manualDuplicateSlide: "Duplicar",
    manualDeleteSlide: "Eliminar",
    manualDeleteSlideConfirm: "¿Estás seguro de que quieres eliminar esta diapositiva?",
    manualSelectLayout: "Seleccionar Diseño",
    manualSearchImages: "Buscar Imágenes",
    manualFullscreen: "Editor a Pantalla Completa",
    manualUndo: "Deshacer",
    manualRedo: "Rehacer",
    manualAlignLeft: "Alinear a la Izquierda",
    manualAlignCenter: "Centrar Horizontalmente",
    manualAlignRight: "Alinear a la Derecha",
    manualAlignTop: "Alinear Arriba",
    manualAlignMiddle: "Centrar Verticalmente",
    manualAlignBottom: "Alinear Abajo",
    manualBringForward: "Traer Adelante",
    manualSendBackward: "Enviar Atrás",
    manualEditText: "Editar Texto",
    manualRemoveElement: "Eliminar Elemento",
    manualNotesHint: "Las notas se pueden deshacer cuando el campo pierde el foco.",
    manualGenerateNotes: "Generar Notas con IA",
    manualGeneratingNotes: "Generando notas...",
    manualWriteNotes: "Escribe notas aquí...",
    manualNoSlides: "Aún no hay diapositivas. Haz clic en 'Añadir Diapositiva' para empezar.",
    manualLayoutTitle: "Diapositiva de Título",
    manualLayoutContent: "Contenido",
    manualLayoutImageText: "Imagen + Texto",
    manualLayoutTwoColumn: "Dos Columnas",
    manualLayoutImageOnly: "Solo Imagen",
    manualLayoutBlank: "En Blanco",
    historyCreated: "Creada",
    historySlides: "diapositivas",
    historyEdit: "Editar",
    historyDelete: "Eliminar",
    historyDeleteConfirm: "¿Estás seguro de que quieres eliminar esta presentación?",
    historySavedAuto: "Guardada en historial",
    historySearch: "Buscar en historial...",
    historyStatusRunning: "En curso",
    historyStatusCompleted: "Completada",
    historyStatusError: "Error",
    historyColTitle: "Título",
    historyColType: "Tipo",
    historyColStatus: "Estado",
    historyColProvider: "Proveedor",
    historyColSlides: "Diapositivas",
    historyColDate: "Fecha",
    historyColActions: "Acciones",
    historyTypePresentation: "Presentación",
    historyTypeNotes: "Notas",
    historyCompleted: "Completadas",
    historyStop: "Detener",
    historyStopConfirm: "¿Estás seguro de que quieres detener esta generación?",
    historyImportManual: "Importar al Creador Manual",
    historyInProgress: "En Curso",
    tabNotes: "Notas",
    notesUploadPptx: "Subir PowerPoint (.pptx)",
    notesUploadDoc: "Subir Documento (PDF, DOCX, TXT)",
    notesDragPptx: "Arrastra tu archivo .pptx",
    notesDragDoc: "Arrastra PDF, DOCX o TXT",
    notesGenerate: "Generar Notas",
    notesGenerating: "Generando notas...",
    notesParsing: "Analizando PowerPoint...",
    notesAnalyzing: "Analizando documento...",
    notesProcessing: "Generando notas para diapositiva",
    notesOf: "de",
    notesDone: "¡Notas generadas!",
    notesSlide: "Diapositiva",
    notesRegenerate: "Regenerar",
    notesRegenerateAll: "Regenerar Todas",
    notesCustomPrompt: "Instrucción personalizada (opcional)",
    notesCustomPromptPlaceholder: "Ej: Amplía los puntos clave, céntrate más en...",
    notesExportPptx: "Exportar PPTX con Notas",
    notesBack: "Volver",
    notesEmpty: "Sube un PowerPoint y un documento para generar notas del presentador.",
    notesIncludeExisting: "Incluir notas existentes del presentador",
    notesIncludeExistingDesc: "Usa las notas existentes como guía para la IA",
    notesUseVision: "Analizar diapositiva visualmente",
    notesUseVisionDesc: "Envía las imágenes de la diapositiva a la IA para un análisis más rico (requiere modelo con visión)",
    notesDocDensity: "Cobertura del documento",
    notesDocDensitySlideOnly: "Solo diapositiva",
    notesDocDensityFull: "Documento completo",
    notesParagraphs: "Párrafos por nota",
    notesParagraphsCustom: "Sin límite",
    notesNoProvider: "Selecciona un proveedor y modelo primero.",
    notesPrompt: "Prompt de Notas",
    imageSearchTitle: "Buscar Imágenes",
    imageSearchPlaceholder: "Buscar imágenes...",
    imageSearchButton: "Buscar",
    imageSearchSource: "Fuente",
    imageSearchAllSources: "Todas las Fuentes",
    imageSearchNoResults: "No se encontraron imágenes. Prueba con otro término.",
    imageSearchSearching: "Buscando...",
    imageSearchSelect: "Seleccionar",
    imageSearchSlot: "Hueco de imagen",
    imageSearchLoadMore: "Cargar más resultados",
    imageSearchLoadingMore: "Cargando más...",
    slideRegenerate: "Regenerar Diapositiva",
    slideRegenerating: "Regenerando...",
    slideVariants: "Generar Variantes",
    slideVariantsCount: "Opciones",
    slideVariantsGenerating: "Generando variantes...",
    slideVariantsTitle: "Variantes de Diapositiva",
    slideVariantsApply: "Usar esta variante",
    slideVariantsNone: "No se generaron variantes.",
    speedOptimizations: "Optimizaciones de Velocidad",
    speedOptimizationsDesc: "Reduce el tiempo de búsqueda de imágenes omitiendo consultas redundantes. Cada opción sacrifica un poco de variedad de imágenes a cambio de mayor velocidad.",
    speedCapFallbacks: "Limitar búsquedas de respaldo",
    speedCapFallbacksDesc: "Limita los reintentos cuando las búsquedas iniciales devuelven pocos resultados.",
    speedCapFallbacksGain: "Elimina la fase más lenta — puede ahorrar 10-30s por generación.",
    speedCapFallbacksLoss: "Diapositivas con temas muy específicos pueden tener menos opciones de imagen.",
    speedSkipCategory: "Omitir búsqueda por categoría",
    speedSkipCategoryDesc: "Desactiva las búsquedas por categoría en Wikimedia (2 llamadas API secuenciales por diapositiva).",
    speedSkipCategoryGain: "Ahorra ~2-5s por diapositiva al eliminar búsquedas redundantes.",
    speedSkipCategoryLoss: "Ligeramente menos resultados para temas amplios/enciclopédicos.",
    speedReduceQueries: "Menos consultas de búsqueda",
    speedReduceQueriesDesc: "Usa 2 variantes de consulta por diapositiva en lugar de 3.",
    speedReduceQueriesGain: "Ahorra ~1-2s por diapositiva al reducir llamadas API.",
    speedReduceQueriesLoss: "Marginalmente menos diversidad de imágenes por diapositiva.",
    speedLowerLimit: "Límite de descarga menor",
    speedLowerLimitDesc: "Descarga menos imágenes candidatas por consulta.",
    speedLowerLimitGain: "Respuestas más rápidas y menos datos que procesar.",
    speedLowerLimitLoss: "Menos opciones para elegir — generalmente imperceptible.",
    speedGain: "Beneficio",
    speedLoss: "Compensación",
    dangerZone: "Zona de Peligro",
    dangerZoneDesc: "Acciones irreversibles. Procede con precaución.",
    dangerRemoveAiKeys: "Eliminar Claves API de IA",
    dangerRemoveAiKeysDesc: "Elimina todas las claves API de proveedores de IA (OpenRouter, Gemini, Claude, OpenAI).",
    dangerRemoveImageKeys: "Eliminar Claves de Imágenes",
    dangerRemoveImageKeysDesc: "Elimina todas las claves API de fuentes de imágenes (Unsplash, Pexels, Pixabay, Flickr, Europeana).",
    dangerRemoveManual: "Eliminar Creaciones Manuales",
    dangerRemoveManualDesc: "Elimina todas las presentaciones creadas manualmente.",
    dangerRemoveAiCreations: "Eliminar Creaciones con IA",
    dangerRemoveAiCreationsDesc: "Elimina todas las presentaciones generadas con IA del historial.",
    dangerRemoveNotes: "Eliminar Notas Generadas",
    dangerRemoveNotesDesc: "Elimina todos los proyectos de notas generadas del historial.",
    dangerRemoveAllCreations: "Eliminar Todas las Creaciones",
    dangerRemoveAllCreationsDesc: "Elimina todas las presentaciones, notas y creaciones manuales.",
    dangerRemoveEverything: "Eliminar Todo",
    dangerRemoveEverythingDesc: "Elimina todos los datos: claves API, creaciones, historial y configuración.",
    dangerConfirmTitle: "¿Estás seguro?",
    dangerConfirmMessage: "Esta acción no se puede deshacer.",
    dangerConfirmButton: "Sí, eliminar",
    dangerSuccess: "Hecho",
  },
} as const;

export type UITextKey = keyof typeof UI_TEXT.en;

export const SLIDE_COUNT_OPTIONS = [5, 10, 15, 30, 50, 100] as const;

export const TEXT_DENSITY_OPTIONS = [0, 5, 10, 30, 50] as const;
