/**
 * Re-export lucide-react icons under the names used across the app.
 * This lets every file keep `import { IconFoo } from "./Icons"` unchanged.
 */
export {
  Palette        as IconPalette,
  AlignLeft      as IconText,
  Mic            as IconMic,
  Settings       as IconSettings,
  Globe          as IconGlobe,
  RefreshCw      as IconRefresh,
  Check          as IconCheck,
  AlertTriangle  as IconWarning,
  ChevronLeft    as IconChevronLeft,
  ChevronRight   as IconChevronRight,
  ArrowLeft      as IconArrowLeft,
  Download       as IconDownload,
  Presentation   as IconSlides,
  Image          as IconImage,
  Send           as IconSend,
  Upload         as IconUpload,
  Hash           as IconHash,
  LayoutGrid     as IconLayout,
  Zap            as IconZap,
  Percent        as IconPercent,
  Grid2X2        as IconGrid,
  Maximize       as IconExpand,
  Droplet        as IconDroplet,
  FileText       as IconFileText,
  Undo2          as IconUndo,
  Sparkles       as IconSparkles,
  Loader2        as IconLoader,
  Wand2          as IconWand,
  Clock          as IconClock,
  Trash2         as IconTrash,
  Pencil         as IconPencil,
  Plus           as IconPlus,
  Search         as IconSearch,
  Square         as IconStop,
  Eye            as IconEye,
  EyeOff         as IconEyeOff,
  Copy           as IconCopy,
  Maximize2      as IconFullscreen,
  Minimize2      as IconMinimize,
  Move           as IconMove,
  ZoomIn         as IconZoomIn,
  ZoomOut        as IconZoomOut,
  RotateCcw      as IconReset,
  Type           as IconType,
  GripVertical   as IconGrip,
  Crop           as IconCrop,
  Save           as IconSave,
  Info           as IconInfo,
  PencilRuler    as IconPencilRuler,
  ImageOff       as IconImageOff,
} from "lucide-react";

